default: &default
 adapter: postgresql
 encoding: unicode
 username: postgres
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: pickybook_development

test:
 <<: *default
 database: pickybook_test

production:
 <<: *default
 database: pickybook_production
